separating edx and caliper logs
ucsd-ets/openedx-caliper-tracking pull request #8
Opened 2019-03-18 11:15 UTC by HamzaIbnFarooq

Now `caliperized logs` will be sent to `/dev/caliper.log` file and edx's default logs will show their default behavior

2019-03-18 13:03 UTC, asamolion requested changes

2019-03-18 13:03 UTC, asamolion commented on openedx_caliper_tracking/processor.py
> +logger_caliper = logging.getLogger('caliper')
Please change the name to `caliper_logger`

2019-03-18 13:03 UTC, asamolion commented on openedx_caliper_tracking/processor.py
>              logger.exception("Missing transformer method implementation for %s" % event.get('event_type'))
use `.format()` for string formatting.

2019-03-18 13:10 UTC, HamzaIbnFarooq commented on openedx_caliper_tracking/processor.py
> +logger_caliper = logging.getLogger('caliper')
done

2019-03-18 13:10 UTC, HamzaIbnFarooq commented on openedx_caliper_tracking/processor.py
>              logger.exception("Missing transformer method implementation for %s" % event.get('event_type'))
done

2019-03-19 06:52 UTC, asamolion commented
Discuss with @danialmalik and finalize an architecture for v1.0 of the app.

2019-03-26 11:13 UTC, asamolion approved these changes

2019-03-26 12:02 UTC, danialmalik approved these changes

2019-03-26 12:07 UTC, merged